//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrumbleApp.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrumbleApp.Shared.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a background task to check for new announcements in the past hour..
        /// </summary>
        public static string AnnouncementBackgroundTaskDescription {
            get {
                return ResourceManager.GetString("AnnouncementBackgroundTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that background agents for this application have been enabled in your phone settings..
        /// </summary>
        public static string AnnouncementBackgrounTaskDisabledPopupText {
            get {
                return ResourceManager.GetString("AnnouncementBackgrounTaskDisabledPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string AnnouncementsLiveTileText {
            get {
                return ResourceManager.GetString("AnnouncementsLiveTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, there is an error in your data, please try again later..
        /// </summary>
        public static string ApiErrorPopupMessageBadRequest {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified email was not found..
        /// </summary>
        public static string ApiErrorPopupMessageEmailNotFound {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, there was an error, but rest assured as we are working on it! Please try again later..
        /// </summary>
        public static string ApiErrorPopupMessageInternalServerError {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pin, please try again..
        /// </summary>
        public static string ApiErrorPopupMessageInvalidPin {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageInvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection and try again..
        /// </summary>
        public static string ApiErrorPopupMessageNoNetwork {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data was found for your region. Please try a different region..
        /// </summary>
        public static string ApiErrorPopupMessageNoResources {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageNoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No route was found for your request..
        /// </summary>
        public static string ApiErrorPopupMessageNoRouteFound {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageNoRouteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, a connection could not be made, please try again later..
        /// </summary>
        public static string ApiErrorPopupMessageNotFound {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string ApiErrorPopupMessageNotFoundError {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not supported in your region..
        /// </summary>
        public static string ApiErrorPopupMessageRegionNotSupported {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageRegionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request took too long, please try again..
        /// </summary>
        public static string ApiErrorPopupMessageTimeout {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorised.
        /// </summary>
        public static string ApiErrorPopupMessageUnauthorizedError {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageUnauthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry, something went wrong, please try again later..
        /// </summary>
        public static string ApiErrorPopupMessageUnknownError {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical update is required to continue using the app. Please check the market place and update your app..
        /// </summary>
        public static string ApiErrorPopupMessageUpdateApp {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageUpdateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been disabled, please contact support for assistance..
        /// </summary>
        public static string ApiErrorPopupMessageUserAccountDeactivated {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageUserAccountDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That user is already authorized and cannot be replaced, you will need to login to continue..
        /// </summary>
        public static string ApiErrorPopupMessageUserAlreadyAuthorised {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageUserAlreadyAuthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user could no longer be found, please try again..
        /// </summary>
        public static string ApiErrorPopupMessageUserNotFound {
            get {
                return ResourceManager.GetString("ApiErrorPopupMessageUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string ApiErrorTaskCancelled {
            get {
                return ResourceManager.GetString("ApiErrorTaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approx Fare.
        /// </summary>
        public static string ApproxCost {
            get {
                return ResourceManager.GetString("ApproxCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.Bumble.com.
        /// </summary>
        public static string CompanyWebsiteLink {
            get {
                return ResourceManager.GetString("CompanyWebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen {0}, is this correct?.
        /// </summary>
        public static string CountrySelectionConfirmationPopupText {
            get {
                return ResourceManager.GetString("CountrySelectionConfirmationPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CustomPopupGenericCancelMessage {
            get {
                return ResourceManager.GetString("CustomPopupGenericCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string CustomPopupGenericGoToSettings {
            get {
                return ResourceManager.GetString("CustomPopupGenericGoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get your location..
        /// </summary>
        public static string CustomPopupGenericGpsFailureMessage {
            get {
                return ResourceManager.GetString("CustomPopupGenericGpsFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services must be enabled to use this feature..
        /// </summary>
        public static string CustomPopupGenericLocationDisabledMessage {
            get {
                return ResourceManager.GetString("CustomPopupGenericLocationDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t show.
        /// </summary>
        public static string CustomPopupGenericMessageDoNotShow {
            get {
                return ResourceManager.GetString("CustomPopupGenericMessageDoNotShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string CustomPopupGenericNoMessage {
            get {
                return ResourceManager.GetString("CustomPopupGenericNoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string CustomPopupGenericNoThanksMessage {
            get {
                return ResourceManager.GetString("CustomPopupGenericNoThanksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok, got it!.
        /// </summary>
        public static string CustomPopupGenericOkGotItMessage {
            get {
                return ResourceManager.GetString("CustomPopupGenericOkGotItMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string CustomPopupGenericOkMessage {
            get {
                return ResourceManager.GetString("CustomPopupGenericOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok, sure!.
        /// </summary>
        public static string CustomPopupGenericOkSureMessage {
            get {
                return ResourceManager.GetString("CustomPopupGenericOkSureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string CustomPopupGenericYesMessage {
            get {
                return ResourceManager.GetString("CustomPopupGenericYesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CustomPopupMessageTypeError {
            get {
                return ResourceManager.GetString("CustomPopupMessageTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string CustomPopupMessageTypeInformation {
            get {
                return ResourceManager.GetString("CustomPopupMessageTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string CustomPopupMessageTypeSuccess {
            get {
                return ResourceManager.GetString("CustomPopupMessageTypeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string CustomPopupMessageTypeWarning {
            get {
                return ResourceManager.GetString("CustomPopupMessageTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last used.
        /// </summary>
        public static string FavouriteLastUsedText {
            get {
                return ResourceManager.GetString("FavouriteLastUsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This trip is already in your favourites..
        /// </summary>
        public static string FavouritesAlreadyExistsErrorPopupText {
            get {
                return ResourceManager.GetString("FavouritesAlreadyExistsErrorPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite removed..
        /// </summary>
        public static string FavouritesRemovedFromFavourites {
            get {
                return ResourceManager.GetString("FavouritesRemovedFromFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ....
        /// </summary>
        public static string FavouritesSearchTextBoxWaterMark {
            get {
                return ResourceManager.GetString("FavouritesSearchTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip added to your favourites..
        /// </summary>
        public static string FavouritesSuccessfullyAddedPopupText {
            get {
                return ResourceManager.GetString("FavouritesSuccessfullyAddedPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HeaderAbout {
            get {
                return ResourceManager.GetString("HeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string HeaderAnnouncements {
            get {
                return ResourceManager.GetString("HeaderAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Destination.
        /// </summary>
        public static string HeaderChooseDestination {
            get {
                return ResourceManager.GetString("HeaderChooseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Location.
        /// </summary>
        public static string HeaderChooseLocation {
            get {
                return ResourceManager.GetString("HeaderChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an Operator.
        /// </summary>
        public static string HeaderChooseOperator {
            get {
                return ResourceManager.GetString("HeaderChooseOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Country.
        /// </summary>
        public static string HeaderCountrySelection {
            get {
                return ResourceManager.GetString("HeaderCountrySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Arrival Time.
        /// </summary>
        public static string HeaderDateTimeArrival {
            get {
                return ResourceManager.GetString("HeaderDateTimeArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Departure Time.
        /// </summary>
        public static string HeaderDateTimeDeparture {
            get {
                return ResourceManager.GetString("HeaderDateTimeDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore your City.
        /// </summary>
        public static string HeaderExploreCity {
            get {
                return ResourceManager.GetString("HeaderExploreCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Trips.
        /// </summary>
        public static string HeaderFavourites {
            get {
                return ResourceManager.GetString("HeaderFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Place Categories.
        /// </summary>
        public static string HeaderFilterPoiCategories {
            get {
                return ResourceManager.GetString("HeaderFilterPoiCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorise.
        /// </summary>
        public static string HeaderIdentify {
            get {
                return ResourceManager.GetString("HeaderIdentify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string HeaderLogin {
            get {
                return ResourceManager.GetString("HeaderLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string HeaderMainMenu {
            get {
                return ResourceManager.GetString("HeaderMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Maps.
        /// </summary>
        public static string HeaderMaps {
            get {
                return ResourceManager.GetString("HeaderMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Drumble.
        /// </summary>
        public static string HeaderMessage {
            get {
                return ResourceManager.GetString("HeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes Filter.
        /// </summary>
        public static string HeaderMode {
            get {
                return ResourceManager.GetString("HeaderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Point A.
        /// </summary>
        public static string HeaderPointA {
            get {
                return ResourceManager.GetString("HeaderPointA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Point B.
        /// </summary>
        public static string HeaderPointB {
            get {
                return ResourceManager.GetString("HeaderPointB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string HeaderProfile {
            get {
                return ResourceManager.GetString("HeaderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Trips.
        /// </summary>
        public static string HeaderRecent {
            get {
                return ResourceManager.GetString("HeaderRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Region.
        /// </summary>
        public static string HeaderRegionSelection {
            get {
                return ResourceManager.GetString("HeaderRegionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string HeaderRegister {
            get {
                return ResourceManager.GetString("HeaderRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Search Text.
        /// </summary>
        public static string HeaderSearch {
            get {
                return ResourceManager.GetString("HeaderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string HeaderSettings {
            get {
                return ResourceManager.GetString("HeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell a Friend.
        /// </summary>
        public static string HeaderShare {
            get {
                return ResourceManager.GetString("HeaderShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Station.
        /// </summary>
        public static string HeaderStationsNearby {
            get {
                return ResourceManager.GetString("HeaderStationsNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Time.
        /// </summary>
        public static string HeaderTimeSelection {
            get {
                return ResourceManager.GetString("HeaderTimeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Details.
        /// </summary>
        public static string HeaderTripDetails {
            get {
                return ResourceManager.GetString("HeaderTripDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Karma.
        /// </summary>
        public static string HeaderTripKarma {
            get {
                return ResourceManager.GetString("HeaderTripKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Selection.
        /// </summary>
        public static string HeaderTripSelection {
            get {
                return ResourceManager.GetString("HeaderTripSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uber Trip Details.
        /// </summary>
        public static string HeaderUberTripDetails {
            get {
                return ResourceManager.GetString("HeaderUberTripDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Trip.
        /// </summary>
        public static string HeaderWhereTo {
            get {
                return ResourceManager.GetString("HeaderWhereTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid pin..
        /// </summary>
        public static string IdentifyNoPinPopupText {
            get {
                return ResourceManager.GetString("IdentifyNoPinPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Pin.
        /// </summary>
        public static string IdentifyOneTimePinWaterMarkText {
            get {
                return ResourceManager.GetString("IdentifyOneTimePinWaterMarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A one time pin has been sent to {0}..
        /// </summary>
        public static string IdentifyOtpSentPopupText {
            get {
                return ResourceManager.GetString("IdentifyOtpSentPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string InvalidEmailAlert {
            get {
                return ResourceManager.GetString("InvalidEmailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pin. It needs to be a {0} digit number..
        /// </summary>
        public static string InvalidOneTimePinAlert {
            get {
                return ResourceManager.GetString("InvalidOneTimePinAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services must be enabled to use this feature, you can enable location services in settings..
        /// </summary>
        public static string LocationAppDisabledErrorMessage {
            get {
                return ResourceManager.GetString("LocationAppDisabledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginEmailTextBoxWaterMark {
            get {
                return ResourceManager.GetString("LoginEmailTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string LoginNoEmailErrorPopupText {
            get {
                return ResourceManager.GetString("LoginNoEmailErrorPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string MainMenuAnnouncementsDelays {
            get {
                return ResourceManager.GetString("MainMenuAnnouncementsDelays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change country.
        /// </summary>
        public static string MainMenuChangeCountry {
            get {
                return ResourceManager.GetString("MainMenuChangeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite &amp; recent trips.
        /// </summary>
        public static string MainMenuFavouritesRecent {
            get {
                return ResourceManager.GetString("MainMenuFavouritesRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drumble.
        /// </summary>
        public static string MainMenuDrumble {
            get {
                return ResourceManager.GetString("MainMenuDrumble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation maps.
        /// </summary>
        public static string MainMenuMaps {
            get {
                return ResourceManager.GetString("MainMenuMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message us.
        /// </summary>
        public static string MainMenuMessageUs {
            get {
                return ResourceManager.GetString("MainMenuMessageUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places of interest.
        /// </summary>
        public static string MainMenuPlacesOfInterest {
            get {
                return ResourceManager.GetString("MainMenuPlacesOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainMenuSettings {
            get {
                return ResourceManager.GetString("MainMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share app.
        /// </summary>
        public static string MainMenuShareApp {
            get {
                return ResourceManager.GetString("MainMenuShareApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations &amp; stops.
        /// </summary>
        public static string MainMenuStationsStops {
            get {
                return ResourceManager.GetString("MainMenuStationsStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Point A.
        /// </summary>
        public static string MapPointSelectionHeaderA {
            get {
                return ResourceManager.GetString("MapPointSelectionHeaderA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Point B.
        /// </summary>
        public static string MapPointSelectionHeaderB {
            get {
                return ResourceManager.GetString("MapPointSelectionHeaderB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press and hold the map to place a point..
        /// </summary>
        public static string MapPointSelectionHelpPopupText {
            get {
                return ResourceManager.GetString("MapPointSelectionHelpPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not placed any points on the map..
        /// </summary>
        public static string MapPointSelectionNoPointsPlacedPopupText {
            get {
                return ResourceManager.GetString("MapPointSelectionNoPointsPlacedPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed point {0}.
        /// </summary>
        public static string MapPointSelectionRemovedPointPopupText {
            get {
                return ResourceManager.GetString("MapPointSelectionRemovedPointPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Operator.
        /// </summary>
        public static string MapsSelectOperatorText {
            get {
                return ResourceManager.GetString("MapsSelectOperatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Phone Number.
        /// </summary>
        public static string MessageUsContactNumberTextBoxWaterMark {
            get {
                return ResourceManager.GetString("MessageUsContactNumberTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string MessageUsEmailTextBoxWaterMark {
            get {
                return ResourceManager.GetString("MessageUsEmailTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string MessageUsNameTextBoxWaterMark {
            get {
                return ResourceManager.GetString("MessageUsNameTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact number..
        /// </summary>
        public static string MessageUsNoContactNumberPopupText {
            get {
                return ResourceManager.GetString("MessageUsNoContactNumberPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        public static string MessageUsNoEmailPopupText {
            get {
                return ResourceManager.GetString("MessageUsNoEmailPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a message..
        /// </summary>
        public static string MessageUsNoMessagePopupText {
            get {
                return ResourceManager.GetString("MessageUsNoMessagePopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        public static string MessageUsNoNamePopupText {
            get {
                return ResourceManager.GetString("MessageUsNoNamePopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to the terms and conditions to enter..
        /// </summary>
        public static string MessageUsSelectTermsAndConditionsPopupText {
            get {
                return ResourceManager.GetString("MessageUsSelectTermsAndConditionsPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string MessageUsSubjectTextBoxWaterMark {
            get {
                return ResourceManager.GetString("MessageUsSubjectTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your feedback..
        /// </summary>
        public static string MessageUsSuccessPopupText {
            get {
                return ResourceManager.GetString("MessageUsSuccessPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your feedback here..
        /// </summary>
        public static string MessageUsTextBoxWaterMark {
            get {
                return ResourceManager.GetString("MessageUsTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat.
        /// </summary>
        public static string ModeBoat {
            get {
                return ResourceManager.GetString("ModeBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string ModeBus {
            get {
                return ResourceManager.GetString("ModeBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Private Transport Mode(s)..
        /// </summary>
        public static string ModePrivateTransportPopupText {
            get {
                return ResourceManager.GetString("ModePrivateTransportPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail.
        /// </summary>
        public static string ModeRail {
            get {
                return ResourceManager.GetString("ModeRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi.
        /// </summary>
        public static string ModeTaxi {
            get {
                return ResourceManager.GetString("ModeTaxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results to display on the map, have you tried searching?.
        /// </summary>
        public static string PlacesOfInterestNoMapResultsPopupText {
            get {
                return ResourceManager.GetString("PlacesOfInterestNoMapResultsPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search places nearby ....
        /// </summary>
        public static string PlacesOfInterestTextBoxWaterMark {
            get {
                return ResourceManager.GetString("PlacesOfInterestTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        public static string PredefinedDepartureTime120 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string PredefinedDepartureTime1440 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime1440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        public static string PredefinedDepartureTime15 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 hours.
        /// </summary>
        public static string PredefinedDepartureTime240 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string PredefinedDepartureTime30 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 minutes.
        /// </summary>
        public static string PredefinedDepartureTime45 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 hours.
        /// </summary>
        public static string PredefinedDepartureTime480 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string PredefinedDepartureTime60 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour 30 minutes.
        /// </summary>
        public static string PredefinedDepartureTime90 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 hours.
        /// </summary>
        public static string PredefinedDepartureTime960 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime960", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string PredefinedDepartureTimeNow {
            get {
                return ResourceManager.GetString("PredefinedDepartureTimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string ProfileLoginPopupButtonText {
            get {
                return ResourceManager.GetString("ProfileLoginPopupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to have an account with us to use this feature. What would you like to do?.
        /// </summary>
        public static string ProfileNotRegisteredPopupText {
            get {
                return ResourceManager.GetString("ProfileNotRegisteredPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string ProfileRegisterPopupButtonText {
            get {
                return ResourceManager.GetString("ProfileRegisterPopupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last used.
        /// </summary>
        public static string RecentLastUsedText {
            get {
                return ResourceManager.GetString("RecentLastUsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip added to your favourites..
        /// </summary>
        public static string RecentTripsAddedToFavourites {
            get {
                return ResourceManager.GetString("RecentTripsAddedToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip removed from your favourites..
        /// </summary>
        public static string RecentTripsRemovedFromFavourites {
            get {
                return ResourceManager.GetString("RecentTripsRemovedFromFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while accessing Facebook, please try again later..
        /// </summary>
        public static string RegisterFacebookErrorPopupText {
            get {
                return ResourceManager.GetString("RegisterFacebookErrorPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ....
        /// </summary>
        public static string SearchStationsAndPlacesOfInterestTextBoxWatermark {
            get {
                return ResourceManager.GetString("SearchStationsAndPlacesOfInterestTextBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Stations ....
        /// </summary>
        public static string SearchStationsTextBoxWaterMark {
            get {
                return ResourceManager.GetString("SearchStationsTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ....
        /// </summary>
        public static string SearchTextBoxWaterMark {
            get {
                return ResourceManager.GetString("SearchTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        public static string SettingsSavedPopupMessage {
            get {
                return ResourceManager.GetString("SettingsSavedPopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a country ....
        /// </summary>
        public static string SplashButtonTextSelectCountry {
            get {
                return ResourceManager.GetString("SplashButtonTextSelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a region ....
        /// </summary>
        public static string SplashButtonTextSelectRegion {
            get {
                return ResourceManager.GetString("SplashButtonTextSelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating policies ....
        /// </summary>
        public static string SplashLoaderTextAbout {
            get {
                return ResourceManager.GetString("SplashLoaderTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string SplashLoaderTextCheckingForUpdates {
            get {
                return ResourceManager.GetString("SplashLoaderTextCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete..
        /// </summary>
        public static string SplashLoaderTextComplete {
            get {
                return ResourceManager.GetString("SplashLoaderTextComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading supported countries ....
        /// </summary>
        public static string SplashLoaderTextCountries {
            get {
                return ResourceManager.GetString("SplashLoaderTextCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading data for: {0} ....
        /// </summary>
        public static string SplashLoaderTextDownloadingCountryData {
            get {
                return ResourceManager.GetString("SplashLoaderTextDownloadingCountryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking API availability ....
        /// </summary>
        public static string SplashLoaderTextRegistration {
            get {
                return ResourceManager.GetString("SplashLoaderTextRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile already pinned to your start..
        /// </summary>
        public static string TileAlreadyPinnedErrorText {
            get {
                return ResourceManager.GetString("TileAlreadyPinnedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrive at {0} ({1}).
        /// </summary>
        public static string TripDetailsArrivingAt {
            get {
                return ResourceManager.GetString("TripDetailsArrivingAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} to {2}.
        /// </summary>
        public static string TripDetailsLiveTileBackText {
            get {
                return ResourceManager.GetString("TripDetailsLiveTileBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip to {0}.
        /// </summary>
        public static string TripDetailsLiveTileText {
            get {
                return ResourceManager.GetString("TripDetailsLiveTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string TripDetailsPlatformText {
            get {
                return ResourceManager.GetString("TripDetailsPlatformText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string TripDetailsVehicleText {
            get {
                return ResourceManager.GetString("TripDetailsVehicleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip arrives the next day..
        /// </summary>
        public static string TripSelectionArriveNextDayWarning {
            get {
                return ResourceManager.GetString("TripSelectionArriveNextDayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip is complete..
        /// </summary>
        public static string TripSelectionCompleteTrip {
            get {
                return ResourceManager.GetString("TripSelectionCompleteTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip departs the next day..
        /// </summary>
        public static string TripSelectionDepartNextDayWarning {
            get {
                return ResourceManager.GetString("TripSelectionDepartNextDayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave in {0}.
        /// </summary>
        public static string TripSelectionLeavingIn {
            get {
                return ResourceManager.GetString("TripSelectionLeavingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave now.
        /// </summary>
        public static string TripSelectionLeavingNow {
            get {
                return ResourceManager.GetString("TripSelectionLeavingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip includes a lengthly wait and arrives the next day..
        /// </summary>
        public static string TripSelectionLongWaitArrivingNextDayWarning {
            get {
                return ResourceManager.GetString("TripSelectionLongWaitArrivingNextDayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip includes a lengthly wait and departs the next day..
        /// </summary>
        public static string TripSelectionLongWaitDepartNextDayWarning {
            get {
                return ResourceManager.GetString("TripSelectionLongWaitDepartNextDayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip includes a lengthly wait..
        /// </summary>
        public static string TripSelectionLongWaitWarning {
            get {
                return ResourceManager.GetString("TripSelectionLongWaitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string TripSelectionMinutes {
            get {
                return ResourceManager.GetString("TripSelectionMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes remain.
        /// </summary>
        public static string TripSelectionMinutesRemain {
            get {
                return ResourceManager.GetString("TripSelectionMinutesRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No alerts for this trip..
        /// </summary>
        public static string TripSelectionNoAlertsPopupText {
            get {
                return ResourceManager.GetString("TripSelectionNoAlertsPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to request an Uber? Note: This will charge your account..
        /// </summary>
        public static string TripSelectionRequestUberPopupText {
            get {
                return ResourceManager.GetString("TripSelectionRequestUberPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string TripSelectionTimeDisplay {
            get {
                return ResourceManager.GetString("TripSelectionTimeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip completed {0} ago..
        /// </summary>
        public static string TripSelectionTripEnded {
            get {
                return ResourceManager.GetString("TripSelectionTripEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip began {0} ago..
        /// </summary>
        public static string TripSelectionTripStarted {
            get {
                return ResourceManager.GetString("TripSelectionTripStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the driver cancelled your request..
        /// </summary>
        public static string UberDriverCanceledPopupText {
            get {
                return ResourceManager.GetString("UberDriverCanceledPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred somewhere in the process, please try again..
        /// </summary>
        public static string UberErrorAuthenticating {
            get {
                return ResourceManager.GetString("UberErrorAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an Uber in {0}..
        /// </summary>
        public static string UberGetAnUberText {
            get {
                return ResourceManager.GetString("UberGetAnUberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Uber ....
        /// </summary>
        public static string UberLoadingText {
            get {
                return ResourceManager.GetString("UberLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but there were no drivers available to fulfill your request..
        /// </summary>
        public static string UberNoDriversPopupText {
            get {
                return ResourceManager.GetString("UberNoDriversPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uber not found..
        /// </summary>
        public static string UberNotFoundText {
            get {
                return ResourceManager.GetString("UberNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been made! This page will continue to monitor your trip..
        /// </summary>
        public static string UberRequestRecievedPopupText {
            get {
                return ResourceManager.GetString("UberRequestRecievedPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to cancel your trip?.
        /// </summary>
        public static string UberTripCancelConfirmPopupText {
            get {
                return ResourceManager.GetString("UberTripCancelConfirmPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trip could not be cancelled anymore..
        /// </summary>
        public static string UberTripCancelFailure {
            get {
                return ResourceManager.GetString("UberTripCancelFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trip was cancelled..
        /// </summary>
        public static string UberTripCancelled {
            get {
                return ResourceManager.GetString("UberTripCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using Uber, your trip will no longer be monitored within the app. You can always use the official Uber app to continue to monitor your trip..
        /// </summary>
        public static string UberTripFinishedPopupText {
            get {
                return ResourceManager.GetString("UberTripFinishedPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string UberTripStatusAccepted {
            get {
                return ResourceManager.GetString("UberTripStatusAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arriving.
        /// </summary>
        public static string UberTripStatusArriving {
            get {
                return ResourceManager.GetString("UberTripStatusArriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string UberTripStatusCompleted {
            get {
                return ResourceManager.GetString("UberTripStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Cancelled.
        /// </summary>
        public static string UberTripStatusDriverCanceled {
            get {
                return ResourceManager.GetString("UberTripStatusDriverCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string UberTripStatusError {
            get {
                return ResourceManager.GetString("UberTripStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string UberTripStatusInProgress {
            get {
                return ResourceManager.GetString("UberTripStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Drivers.
        /// </summary>
        public static string UberTripStatusNoDrivers {
            get {
                return ResourceManager.GetString("UberTripStatusNoDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string UberTripStatusProcessing {
            get {
                return ResourceManager.GetString("UberTripStatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting.
        /// </summary>
        public static string UberTripStatusRequesting {
            get {
                return ResourceManager.GetString("UberTripStatusRequesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string UberTripStatusRiderCanceled {
            get {
                return ResourceManager.GetString("UberTripStatusRiderCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorised.
        /// </summary>
        public static string UberTripStatusUnauthorized {
            get {
                return ResourceManager.GetString("UberTripStatusUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown address..
        /// </summary>
        public static string UnkownAddress {
            get {
                return ResourceManager.GetString("UnkownAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait.
        /// </summary>
        public static string WaitingStageName {
            get {
                return ResourceManager.GetString("WaitingStageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrive {0}.
        /// </summary>
        public static string WhereToArrivingAtText {
            get {
                return ResourceManager.GetString("WhereToArrivingAtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arriving in {0}.
        /// </summary>
        public static string WhereToArrivingInText {
            get {
                return ResourceManager.GetString("WhereToArrivingInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arriving {0}.
        /// </summary>
        public static string WhereToArrivingText {
            get {
                return ResourceManager.GetString("WhereToArrivingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue my last trip..
        /// </summary>
        public static string WhereToContinueTripButtonText {
            get {
                return ResourceManager.GetString("WhereToContinueTripButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue my Uber trip..
        /// </summary>
        public static string WhereToContinueUberTripButtonText {
            get {
                return ResourceManager.GetString("WhereToContinueUberTripButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your departure date cannot be in the past..
        /// </summary>
        public static string WhereToCustomDateErrorPopupText {
            get {
                return ResourceManager.GetString("WhereToCustomDateErrorPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depart {0}.
        /// </summary>
        public static string WhereToDepartingAtText {
            get {
                return ResourceManager.GetString("WhereToDepartingAtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departing in {0}.
        /// </summary>
        public static string WhereToDepartingInText {
            get {
                return ResourceManager.GetString("WhereToDepartingInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departing {0}.
        /// </summary>
        public static string WhereToDepartingText {
            get {
                return ResourceManager.GetString("WhereToDepartingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid destination..
        /// </summary>
        public static string WhereToDestinationErrorPopupText {
            get {
                return ResourceManager.GetString("WhereToDestinationErrorPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string WhereToDestinationTextBoxWaterMark {
            get {
                return ResourceManager.GetString("WhereToDestinationTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations &amp; stops.
        /// </summary>
        public static string WhereToDropdownOptionClosestStops {
            get {
                return ResourceManager.GetString("WhereToDropdownOptionClosestStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my location.
        /// </summary>
        public static string WhereToDropdownOptionCurrentLocation {
            get {
                return ResourceManager.GetString("WhereToDropdownOptionCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search places.
        /// </summary>
        public static string WhereToDropdownOptionJustSearch {
            get {
                return ResourceManager.GetString("WhereToDropdownOptionJustSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find on map.
        /// </summary>
        public static string WhereToDropdownOptionSelectOnMap {
            get {
                return ResourceManager.GetString("WhereToDropdownOptionSelectOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding address ....
        /// </summary>
        public static string WhereToFindingAddressWaterMark {
            get {
                return ResourceManager.GetString("WhereToFindingAddressWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding location ....
        /// </summary>
        public static string WhereToFindingLocationTextBoxWaterMark {
            get {
                return ResourceManager.GetString("WhereToFindingLocationTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid location..
        /// </summary>
        public static string WhereToLocationErrorPopupText {
            get {
                return ResourceManager.GetString("WhereToLocationErrorPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string WhereToLocationTextBoxWaterMark {
            get {
                return ResourceManager.GetString("WhereToLocationTextBoxWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include at least one mode of transport in your request..
        /// </summary>
        public static string WhereToNoModesErrorPopupText {
            get {
                return ResourceManager.GetString("WhereToNoModesErrorPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string WhereToNoResultsFound {
            get {
                return ResourceManager.GetString("WhereToNoResultsFound", resourceCulture);
            }
        }
    }
}
