//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drumble.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drumble.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Info.
        /// </summary>
        public static string AboutAppInfo {
            get {
                return ResourceManager.GetString("AboutAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AboutClose {
            get {
                return ResourceManager.GetString("AboutClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string AboutDeveloper {
            get {
                return ResourceManager.GetString("AboutDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string AboutPolicies {
            get {
                return ResourceManager.GetString("AboutPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string AboutPolicyHereButtonText {
            get {
                return ResourceManager.GetString("AboutPolicyHereButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your privacy is important to us. This application uses your location to improve your transport experience. This may be stored and shared, however you may disable &apos;Location Services&apos; under.
        /// </summary>
        public static string AboutPolicyPart1 {
            get {
                return ResourceManager.GetString("AboutPolicyPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumble (Pty) Ltd. will not use this information to contact you in any way..
        /// </summary>
        public static string AboutPolicyPart2 {
            get {
                return ResourceManager.GetString("AboutPolicyPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumble (Pty) Ltd. is committed to protecting the security of your personal information. All data is stored and transferred securely. If you have further questions, contact us.
        /// </summary>
        public static string AboutPolicyPart3 {
            get {
                return ResourceManager.GetString("AboutPolicyPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AboutPolicySettingsText {
            get {
                return ResourceManager.GetString("AboutPolicySettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date:.
        /// </summary>
        public static string AboutReleaseDate {
            get {
                return ResourceManager.GetString("AboutReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New in this release:.
        /// </summary>
        public static string AboutReleaseDetails {
            get {
                return ResourceManager.GetString("AboutReleaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can request an Uber without leaving the app!.
        /// </summary>
        public static string AboutReleaseNotes1 {
            get {
                return ResourceManager.GetString("AboutReleaseNotes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Re Yeng competition removed..
        /// </summary>
        public static string AboutReleaseNotes2 {
            get {
                return ResourceManager.GetString("AboutReleaseNotes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now sign in with your Uber account..
        /// </summary>
        public static string AboutReleaseNotes3 {
            get {
                return ResourceManager.GetString("AboutReleaseNotes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to multimodal transport! Find your way from A to B using any combination of bus, rail, boat and taxi..
        /// </summary>
        public static string AboutReleaseNotes4 {
            get {
                return ResourceManager.GetString("AboutReleaseNotes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide this menu.
        /// </summary>
        public static string AnnouncementsHideMenu {
            get {
                return ResourceManager.GetString("AnnouncementsHideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin announcements.
        /// </summary>
        public static string AnnouncementsPin {
            get {
                return ResourceManager.GetString("AnnouncementsPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string CustomPopupGenericOkMessage {
            get {
                return ResourceManager.GetString("CustomPopupGenericOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string CustomPopupMessageTypeInformation {
            get {
                return ResourceManager.GetString("CustomPopupMessageTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string CustomPopupMessageTypeWarning {
            get {
                return ResourceManager.GetString("CustomPopupMessageTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arriving.
        /// </summary>
        public static string DateTimeSelectionArrivingText {
            get {
                return ResourceManager.GetString("DateTimeSelectionArrivingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string DateTimeSelectionDateText {
            get {
                return ResourceManager.GetString("DateTimeSelectionDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departing.
        /// </summary>
        public static string DateTimeSelectionDepartingText {
            get {
                return ResourceManager.GetString("DateTimeSelectionDepartingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Intervals.
        /// </summary>
        public static string DateTimeSelectionIntervalText {
            get {
                return ResourceManager.GetString("DateTimeSelectionIntervalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Picker.
        /// </summary>
        public static string DateTimeSelectionSpecifyDateText {
            get {
                return ResourceManager.GetString("DateTimeSelectionSpecifyDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string DateTimeSelectionTimeText {
            get {
                return ResourceManager.GetString("DateTimeSelectionTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb.
        /// </summary>
        public static string DebugMegabytes {
            get {
                return ResourceManager.GetString("DebugMegabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to exit?.
        /// </summary>
        public static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string FavouritesLoading {
            get {
                return ResourceManager.GetString("FavouritesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string FavouritesNoResults {
            get {
                return ResourceManager.GetString("FavouritesNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string FooterAlerts {
            get {
                return ResourceManager.GetString("FooterAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string FooterFavourites {
            get {
                return ResourceManager.GetString("FooterFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Karma.
        /// </summary>
        public static string FooterGetKarma {
            get {
                return ResourceManager.GetString("FooterGetKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string FooterRecent {
            get {
                return ResourceManager.GetString("FooterRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share App.
        /// </summary>
        public static string FooterShareApp {
            get {
                return ResourceManager.GetString("FooterShareApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Options.
        /// </summary>
        public static string FooterTripOptions {
            get {
                return ResourceManager.GetString("FooterTripOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HeaderAbout {
            get {
                return ResourceManager.GetString("HeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string HeaderAnnouncements {
            get {
                return ResourceManager.GetString("HeaderAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Country.
        /// </summary>
        public static string HeaderCountrySelection {
            get {
                return ResourceManager.GetString("HeaderCountrySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Departure Time.
        /// </summary>
        public static string HeaderDateTimeSelection {
            get {
                return ResourceManager.GetString("HeaderDateTimeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore your City.
        /// </summary>
        public static string HeaderExploreCity {
            get {
                return ResourceManager.GetString("HeaderExploreCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Trips.
        /// </summary>
        public static string HeaderFavourites {
            get {
                return ResourceManager.GetString("HeaderFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Place Categories.
        /// </summary>
        public static string HeaderFilterPoiCategories {
            get {
                return ResourceManager.GetString("HeaderFilterPoiCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorise.
        /// </summary>
        public static string HeaderIdentify {
            get {
                return ResourceManager.GetString("HeaderIdentify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string HeaderLogin {
            get {
                return ResourceManager.GetString("HeaderLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string HeaderMainMenu {
            get {
                return ResourceManager.GetString("HeaderMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Maps.
        /// </summary>
        public static string HeaderMaps {
            get {
                return ResourceManager.GetString("HeaderMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Drumble.
        /// </summary>
        public static string HeaderMessage {
            get {
                return ResourceManager.GetString("HeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes Filter.
        /// </summary>
        public static string HeaderMode {
            get {
                return ResourceManager.GetString("HeaderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string HeaderProfile {
            get {
                return ResourceManager.GetString("HeaderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Trips.
        /// </summary>
        public static string HeaderRecent {
            get {
                return ResourceManager.GetString("HeaderRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Region.
        /// </summary>
        public static string HeaderRegionSelection {
            get {
                return ResourceManager.GetString("HeaderRegionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string HeaderRegister {
            get {
                return ResourceManager.GetString("HeaderRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Search Text.
        /// </summary>
        public static string HeaderSearch {
            get {
                return ResourceManager.GetString("HeaderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string HeaderSettings {
            get {
                return ResourceManager.GetString("HeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell a Friend.
        /// </summary>
        public static string HeaderShare {
            get {
                return ResourceManager.GetString("HeaderShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Station.
        /// </summary>
        public static string HeaderStationsNearby {
            get {
                return ResourceManager.GetString("HeaderStationsNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Time.
        /// </summary>
        public static string HeaderTimeSelection {
            get {
                return ResourceManager.GetString("HeaderTimeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Details.
        /// </summary>
        public static string HeaderTripDetails {
            get {
                return ResourceManager.GetString("HeaderTripDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Karma.
        /// </summary>
        public static string HeaderTripKarma {
            get {
                return ResourceManager.GetString("HeaderTripKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Selection.
        /// </summary>
        public static string HeaderTripSelection {
            get {
                return ResourceManager.GetString("HeaderTripSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Trip.
        /// </summary>
        public static string HeaderWhereTo {
            get {
                return ResourceManager.GetString("HeaderWhereTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorise.
        /// </summary>
        public static string IdentifyAuthoriseButtonText {
            get {
                return ResourceManager.GetString("IdentifyAuthoriseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string IdentifyCancelButtonText {
            get {
                return ResourceManager.GetString("IdentifyCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Pin.
        /// </summary>
        public static string IdentifyResendPinButtonText {
            get {
                return ResourceManager.GetString("IdentifyResendPinButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click ok to go to your location settings and turn location services on..
        /// </summary>
        public static string LocationPhoneDisabledHelpAlert {
            get {
                return ResourceManager.GetString("LocationPhoneDisabledHelpAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Disabled.
        /// </summary>
        public static string LocationPhoneDisabledHelpCaption {
            get {
                return ResourceManager.GetString("LocationPhoneDisabledHelpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services are not functioning on your device..
        /// </summary>
        public static string LocationPhoneErrorHelpAlert {
            get {
                return ResourceManager.GetString("LocationPhoneErrorHelpAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LoginCloseButtonText {
            get {
                return ResourceManager.GetString("LoginCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In with Facebook.
        /// </summary>
        public static string LoginFacebook {
            get {
                return ResourceManager.GetString("LoginFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already used the app before? Have you changed devices or do you simply want to sync your settings across your devices? Choose the option you used to sign into the app on another device..
        /// </summary>
        public static string LoginHelpTextPart1 {
            get {
                return ResourceManager.GetString("LoginHelpTextPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: You must have created an account or signed in with us before to use this feature..
        /// </summary>
        public static string LoginHelpTextPart2 {
            get {
                return ResourceManager.GetString("LoginHelpTextPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request One Time Pin.
        /// </summary>
        public static string LoginRequestPin {
            get {
                return ResourceManager.GetString("LoginRequestPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In with Twitter.
        /// </summary>
        public static string LoginTwitter {
            get {
                return ResourceManager.GetString("LoginTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to Uber.
        /// </summary>
        public static string LoginUberPopupText {
            get {
                return ResourceManager.GetString("LoginUberPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GPS.
        /// </summary>
        public static string MainMenuEnableGpsPopupText {
            get {
                return ResourceManager.GetString("MainMenuEnableGpsPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync settings and more.
        /// </summary>
        public static string MainMenuSignUpPopupText {
            get {
                return ResourceManager.GetString("MainMenuSignUpPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MapPointSelectionCancelButtonText {
            get {
                return ResourceManager.GetString("MapPointSelectionCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Point A.
        /// </summary>
        public static string MapPointSelectionHeaderA {
            get {
                return ResourceManager.GetString("MapPointSelectionHeaderA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Point B.
        /// </summary>
        public static string MapPointSelectionHeaderB {
            get {
                return ResourceManager.GetString("MapPointSelectionHeaderB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string MapPointSelectionPointText {
            get {
                return ResourceManager.GetString("MapPointSelectionPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string MapPointSelectionSubmitButtonText {
            get {
                return ResourceManager.GetString("MapPointSelectionSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate the app.
        /// </summary>
        public static string MessageUsRateAppPopupText {
            get {
                return ResourceManager.GetString("MessageUsRateAppPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using our app..
        /// </summary>
        public static string MessageUsThankYouTextPart1 {
            get {
                return ResourceManager.GetString("MessageUsThankYouTextPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave us a message to let us know what you think..
        /// </summary>
        public static string MessageUsThankYouTextPart2 {
            get {
                return ResourceManager.GetString("MessageUsThankYouTextPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy commuting..
        /// </summary>
        public static string MessageUsThankYouTextPart3 {
            get {
                return ResourceManager.GetString("MessageUsThankYouTextPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Drumble Team :).
        /// </summary>
        public static string MessageUsThankYouTextPart4 {
            get {
                return ResourceManager.GetString("MessageUsThankYouTextPart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes.
        /// </summary>
        public static string ModeButtonText {
            get {
                return ResourceManager.GetString("ModeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ModeCancelButtonText {
            get {
                return ResourceManager.GetString("ModeCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string ModePrivateText {
            get {
                return ResourceManager.GetString("ModePrivateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Transport.
        /// </summary>
        public static string ModePrivateTransport {
            get {
                return ResourceManager.GetString("ModePrivateTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Transport.
        /// </summary>
        public static string ModePublicTransport {
            get {
                return ResourceManager.GetString("ModePublicTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ModeSaveButtonText {
            get {
                return ResourceManager.GetString("ModeSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PlacesOfInterestCancelButtonText {
            get {
                return ResourceManager.GetString("PlacesOfInterestCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string PlacesOfInterestDirectionsButtonText {
            get {
                return ResourceManager.GetString("PlacesOfInterestDirectionsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Trip.
        /// </summary>
        public static string PlacesOfInterestFindTripButtonText {
            get {
                return ResourceManager.GetString("PlacesOfInterestFindTripButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string PlacesOfInterestListButtonText {
            get {
                return ResourceManager.GetString("PlacesOfInterestListButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string PlacesOfInterestMapButtonText {
            get {
                return ResourceManager.GetString("PlacesOfInterestMapButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string PlacesOfInterestNoResults {
            get {
                return ResourceManager.GetString("PlacesOfInterestNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PlacesOfInterestSaveButtonText {
            get {
                return ResourceManager.GetString("PlacesOfInterestSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Trips.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorise using any of the below methods to unlock features, securely store your preferences, trips and favourites..
        /// </summary>
        public static string RegisterHelpText {
            get {
                return ResourceManager.GetString("RegisterHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recent trips..
        /// </summary>
        public static string SeachNoRecentTrips {
            get {
                return ResourceManager.GetString("SeachNoRecentTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        public static string SearchCurrentLocation {
            get {
                return ResourceManager.GetString("SearchCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find on map.
        /// </summary>
        public static string SearchFindOnMap {
            get {
                return ResourceManager.GetString("SearchFindOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a trip:.
        /// </summary>
        public static string SelectATripText {
            get {
                return ResourceManager.GetString("SelectATripText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always loads your current location when you start the app..
        /// </summary>
        public static string SesttingsPopulateLocationDescription {
            get {
                return ResourceManager.GetString("SesttingsPopulateLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change country.
        /// </summary>
        public static string SettingsChangeCountry {
            get {
                return ResourceManager.GetString("SettingsChangeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsCloseButtonText {
            get {
                return ResourceManager.GetString("SettingsCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable TripKarma.
        /// </summary>
        public static string SettingsEnableTripKarma {
            get {
                return ResourceManager.GetString("SettingsEnableTripKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know your carbon footprint, see trip stats and access extra app features..
        /// </summary>
        public static string SettingsEnableTripKarmaDescription {
            get {
                return ResourceManager.GetString("SettingsEnableTripKarmaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find places close to you and remain informed en route..
        /// </summary>
        public static string SettingsLocationServiceDescription {
            get {
                return ResourceManager.GetString("SettingsLocationServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow location services.
        /// </summary>
        public static string SettingsLocationServiceText {
            get {
                return ResourceManager.GetString("SettingsLocationServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to Uber.
        /// </summary>
        public static string SettingsLoginUber {
            get {
                return ResourceManager.GetString("SettingsLoginUber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your Uber account to request an Uber from within the app. Disable this option to logout of your Uber account..
        /// </summary>
        public static string SettingsLoginUberDescription {
            get {
                return ResourceManager.GetString("SettingsLoginUberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Metric system.
        /// </summary>
        public static string SettingsMetric {
            get {
                return ResourceManager.GetString("SettingsMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use kilometers &amp; meters, if disabled Imperial system is used (miles &amp; yards)..
        /// </summary>
        public static string SettingsMetricDescription {
            get {
                return ResourceManager.GetString("SettingsMetricDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with my location.
        /// </summary>
        public static string SettingsPopulateLocation {
            get {
                return ResourceManager.GetString("SettingsPopulateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with most frequent trip.
        /// </summary>
        public static string SettingsPopulateMostUsed {
            get {
                return ResourceManager.GetString("SettingsPopulateMostUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always loads your most frequent trip when you start the app..
        /// </summary>
        public static string SettingsPopulateMostUsedDescription {
            get {
                return ResourceManager.GetString("SettingsPopulateMostUsedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with my most recent trip.
        /// </summary>
        public static string SettingsPopulateRecent {
            get {
                return ResourceManager.GetString("SettingsPopulateRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always loads your most recent trip when you start the app..
        /// </summary>
        public static string SettingsPopulateRecentDescription {
            get {
                return ResourceManager.GetString("SettingsPopulateRecentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset app.
        /// </summary>
        public static string SettingsResetApp {
            get {
                return ResourceManager.GetString("SettingsResetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve app.
        /// </summary>
        public static string SettingsSendUsageStats {
            get {
                return ResourceManager.GetString("SettingsSendUsageStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send us usage stats from time-to-time..
        /// </summary>
        public static string SettingsSendUsageStatsDescription {
            get {
                return ResourceManager.GetString("SettingsSendUsageStatsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pin announcements.
        /// </summary>
        public static string SettingsShowAnnouncementApplicationBar {
            get {
                return ResourceManager.GetString("SettingsShowAnnouncementApplicationBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the Windows Phone menu to allow you to pin announcements to your start.  .
        /// </summary>
        public static string SettingsShowAnnouncementApplicationBarDescription {
            get {
                return ResourceManager.GetString("SettingsShowAnnouncementApplicationBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show intermittent stops.
        /// </summary>
        public static string SettingsShowIntermittentStops {
            get {
                return ResourceManager.GetString("SettingsShowIntermittentStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate all the stations along my route..
        /// </summary>
        public static string SettingsShowIntermittentStopsDescription {
            get {
                return ResourceManager.GetString("SettingsShowIntermittentStopsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pin trip.
        /// </summary>
        public static string SettingsShowTripApplicationBar {
            get {
                return ResourceManager.GetString("SettingsShowTripApplicationBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the Windows Phone menu to allow you to pin trips to your start..
        /// </summary>
        public static string SettingsShowTripApplicationBarDescription {
            get {
                return ResourceManager.GetString("SettingsShowTripApplicationBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show weather.
        /// </summary>
        public static string SettingsShowWeather {
            get {
                return ResourceManager.GetString("SettingsShowWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the weather in the header of the app. Weather is updated hourly..
        /// </summary>
        public static string SettingsShowWeatherDescription {
            get {
                return ResourceManager.GetString("SettingsShowWeatherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip trip selection.
        /// </summary>
        public static string SettingsSkipTripSelection {
            get {
                return ResourceManager.GetString("SettingsSkipTripSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go directly to the detail view when searching a trip. Note: You will not be presented with an Uber option when this setting is enabled..
        /// </summary>
        public static string SettingsSkipTripSelectionDescription {
            get {
                return ResourceManager.GetString("SettingsSkipTripSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep history.
        /// </summary>
        public static string SettingsStoreRecent {
            get {
                return ResourceManager.GetString("SettingsStoreRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store your trips locally on your phone. Disable this option to delete existing trips..
        /// </summary>
        public static string SettingsStoreRecentDescription {
            get {
                return ResourceManager.GetString("SettingsStoreRecentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Uber.
        /// </summary>
        public static string SettingsUber {
            get {
                return ResourceManager.GetString("SettingsUber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always displays the fastest and cheapest Uber option below your public transport results..
        /// </summary>
        public static string SettingsUberDescription {
            get {
                return ResourceManager.GetString("SettingsUberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://get.Drumbleapp.com.
        /// </summary>
        public static string ShareLink {
            get {
                return ResourceManager.GetString("ShareLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! I&apos;m using Drumble for all my public transport needs, you should check it out -.
        /// </summary>
        public static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your junk mail if you do not receive a pin soon..
        /// </summary>
        public static string SpamMailWarning {
            get {
                return ResourceManager.GetString("SpamMailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, please.
        /// </summary>
        public static string SplashScreenConnectionErrorTextPart1 {
            get {
                return ResourceManager.GetString("SplashScreenConnectionErrorTextPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap here to try again..
        /// </summary>
        public static string SplashScreenConnectionErrorTextPart2 {
            get {
                return ResourceManager.GetString("SplashScreenConnectionErrorTextPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SplashScreenSignInText {
            get {
                return ResourceManager.GetString("SplashScreenSignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Stations ....
        /// </summary>
        public static string StationsNearbyLoadingStations {
            get {
                return ResourceManager.GetString("StationsNearbyLoadingStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Stations ....
        /// </summary>
        public static string StopSelectionLoadingStations {
            get {
                return ResourceManager.GetString("StopSelectionLoadingStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Trip.
        /// </summary>
        public static string TripDetailsBeginTripButtonText {
            get {
                return ResourceManager.GetString("TripDetailsBeginTripButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TripDetailsCancelTripButtonText {
            get {
                return ResourceManager.GetString("TripDetailsCancelTripButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide this menu.
        /// </summary>
        public static string TripDetailsHideMenu {
            get {
                return ResourceManager.GetString("TripDetailsHideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin this trip.
        /// </summary>
        public static string TripDetailsPin {
            get {
                return ResourceManager.GetString("TripDetailsPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view map.
        /// </summary>
        public static string TripDetailsViewMap {
            get {
                return ResourceManager.GetString("TripDetailsViewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UberCancelButton {
            get {
                return ResourceManager.GetString("UberCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UberCancelButtonText {
            get {
                return ResourceManager.GetString("UberCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fake Surge.
        /// </summary>
        public static string UberFakeSurgeButton {
            get {
                return ResourceManager.GetString("UberFakeSurgeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string UberFinishButtonText {
            get {
                return ResourceManager.GetString("UberFinishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string UberRefreshButton {
            get {
                return ResourceManager.GetString("UberRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string UberRetryButton {
            get {
                return ResourceManager.GetString("UberRetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string UberRetryButtonText {
            get {
                return ResourceManager.GetString("UberRetryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surge pricing is in effect, please confirm..
        /// </summary>
        public static string UberSurgePricingConfirmationPopupText {
            get {
                return ResourceManager.GetString("UberSurgePricingConfirmationPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver:.
        /// </summary>
        public static string UberTripDetailsDriver {
            get {
                return ResourceManager.GetString("UberTripDetailsDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Phone Number:.
        /// </summary>
        public static string UberTripDetailsDriverPhoneNumber {
            get {
                return ResourceManager.GetString("UberTripDetailsDriverPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Picture:.
        /// </summary>
        public static string UberTripDetailsDriverPicture {
            get {
                return ResourceManager.GetString("UberTripDetailsDriverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA:.
        /// </summary>
        public static string UberTripDetailsETA {
            get {
                return ResourceManager.GetString("UberTripDetailsETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Uber Trip:.
        /// </summary>
        public static string UberTripDetailsText {
            get {
                return ResourceManager.GetString("UberTripDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Status:.
        /// </summary>
        public static string UberTripDetailsTripStatus {
            get {
                return ResourceManager.GetString("UberTripDetailsTripStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate:.
        /// </summary>
        public static string UberTripDetailsVehicleLicense {
            get {
                return ResourceManager.GetString("UberTripDetailsVehicleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle:.
        /// </summary>
        public static string UberTripDetailsVehicleMake {
            get {
                return ResourceManager.GetString("UberTripDetailsVehicleMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string UserLocationMarkerText {
            get {
                return ResourceManager.GetString("UserLocationMarkerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drumble.
        /// </summary>
        public static string WhereToDrumbleButtonText {
            get {
                return ResourceManager.GetString("WhereToDrumbleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WhereToDrumbleCancelButtonText {
            get {
                return ResourceManager.GetString("WhereToDrumbleCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to?.
        /// </summary>
        public static string WhereToText {
            get {
                return ResourceManager.GetString("WhereToText", resourceCulture);
            }
        }
    }
}
