//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrumbleApp.Domain.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrumbleApp.Domain.Models.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        public static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from now.
        /// </summary>
        public static string FromNow {
            get {
                return ResourceManager.GetString("FromNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string HourAbbr {
            get {
                return ResourceManager.GetString("HourAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string InvalidEmailAlert {
            get {
                return ResourceManager.GetString("InvalidEmailAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string KilometersAbbr {
            get {
                return ResourceManager.GetString("KilometersAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string MetersAbbr {
            get {
                return ResourceManager.GetString("MetersAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string MilesAbbr {
            get {
                return ResourceManager.GetString("MilesAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string MinuteAbbr {
            get {
                return ResourceManager.GetString("MinuteAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PopupMessageTypeError {
            get {
                return ResourceManager.GetString("PopupMessageTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string PopupMessageTypeInformation {
            get {
                return ResourceManager.GetString("PopupMessageTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string PopupMessageTypeSuccess {
            get {
                return ResourceManager.GetString("PopupMessageTypeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string PopupMessageTypeWarning {
            get {
                return ResourceManager.GetString("PopupMessageTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 hours.
        /// </summary>
        public static string PredefinedDepartureTime120 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string PredefinedDepartureTime1440 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime1440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        public static string PredefinedDepartureTime15 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 hours.
        /// </summary>
        public static string PredefinedDepartureTime240 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes.
        /// </summary>
        public static string PredefinedDepartureTime30 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 minutes.
        /// </summary>
        public static string PredefinedDepartureTime45 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 hours.
        /// </summary>
        public static string PredefinedDepartureTime480 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string PredefinedDepartureTime60 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour 30 minutes.
        /// </summary>
        public static string PredefinedDepartureTime90 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 hours.
        /// </summary>
        public static string PredefinedDepartureTime960 {
            get {
                return ResourceManager.GetString("PredefinedDepartureTime960", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string PredefinedDepartureTimeNow {
            get {
                return ResourceManager.GetString("PredefinedDepartureTimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right now.
        /// </summary>
        public static string RightNow {
            get {
                return ResourceManager.GetString("RightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait.
        /// </summary>
        public static string WaitingStageName {
            get {
                return ResourceManager.GetString("WaitingStageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yds.
        /// </summary>
        public static string YardsAbbr {
            get {
                return ResourceManager.GetString("YardsAbbr", resourceCulture);
            }
        }
    }
}
